name: Main workflow

on: push

env: # Set the secret as an input
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }} #Nees to be set to be made available to the workflow
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest

    needs: [Linting, Snyk-check]
    
    container: gradle:6-jdk11
    
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
    
      - name: Build application
        run: ci/build-app.sh
      
      - name: Test
        run: ci/unit-test-app.sh
      
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  
  Linting:
    runs-on: ubuntu-latest
    
    # needs: [Build]
    
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      
      - name: run linting
        uses: super-linter/super-linter/slim@v5 
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true      
  
  Docker-image:
    runs-on: ubuntu-latest
    
    needs: [Build]
    
    permissions:
      packages: write
    
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
    
      - name: ls
        run: ls -la ci
    
      - name: build docker
        run: bash ci/build-docker.sh
    
      - name: push docker
        run: bash ci/push-docker.sh
  
  Snyk-check:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install Snyk with npm
        run: npm install snyk -g
      - name: snyk test
    
  Trivy-check:
    runs-on: ubuntu-latest

    needs: [Docker-image]

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Run Trivy
        run: trivy image python:3.4-alpine



